datastore:
  kind: mdp
  config_path: era_test.datastore.yaml 
training:
  state_feature_weighting:
    __config_class__: ManualStateFeatureWeighting
    weights:
      u850.0hPa: 1.0
      v850.0hPa: 1.0

